export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const GET_CREW_RIDES_START = 'GET_CREW_RIDES_START';
export const GET_CREW_RIDES_SUCCESS = "GET_CREW_RIDES_SUCCESS";
export const GET_CREW_RIDES_FAILURE = "GET_CREW_RIDES_FAILURE";

export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const UPDATE_RIDE_STATUS_START = 'UPDATE_RIDE_STATUS_START';
export const UPDATE_RIDE_STATUS_SUCCESS = "UPDATE_RIDE_STATUS_SUCCESS";
export const UPDATE_RIDE_STATUS_FAILURE = "UPDATE_RIDE_STATUS_FAILURE";

export const LOGOUT = 'LOGOUT';

export const LOGOUT_USER = 'LOGOUT_USER'


export const DARK_MODE = 'DARK_MODE'
export const LIGHT_MODE = 'LIGHT_MODE'